#! /bin/sh

# 1. Making classpath
classpath="target/classes"

for file in `ls target/lib`
do
	classpath="$classpath:target/lib/$file"
done

# 2. Set the main
main=com.thinkingcloud.tools.js.runner.main.JSRunnerApplication

# 3. Run it
java $DEBUG -cp "$classpath" -Dfile.encoding=UTF8 $main $*